// Project
import type { ActionType } from '@common/enums'

export const localizationForActionType = new Map<ActionType, string>([
  ['IMPORT', 'импортировать'],
  ['CREATE_ROLE', 'создать роль'],
  ['UPDATE_ROLE', 'обновить роль'],
  ['DELETE_ROLE_UNSAFE', 'удалить роль (unsafe)'],
  ['DELETE_ROLE', 'удалить роль'],
  ['DELETE_ROLES_UNSAFE', 'удалить роли (unsafe)'],
  ['DELETE_ROLES', 'удалить роли'],
  ['CREATE_USER', 'создать пользователя'],
  ['UPDATE_USER', 'обновить пользователя'],
  ['DELETE_USER', 'удалить пользователя'],
  ['DELETE_USERS', 'удалить пользователей'],
  ['CREATE_TAG', 'создать тег'],
  ['UPDATE_TAG', 'обновить тег'],
  ['DELETE_TAG', 'удалить тег'],
  ['DELETE_TAGS', 'удалить теги'],
  ['CREATE_DOCUMENT', 'создать документ'],
  ['UPDATE_DOCUMENT', 'обновить документы'],
  ['DELETE_DOCUMENT_UNSAFE', 'удалить документ (unsafe)'],
  ['DELETE_DOCUMENT', 'удалить документ'],
  ['DELETE_DOCUMENTS_UNSAFE', 'удалить документы (unsafe)'],
  ['DELETE_DOCUMENTS', 'удалить документы'],
  ['CREATE_FRAGMENT', 'создать фрагмент документа'],
  ['UPDATE_FRAGMENT', 'обновить фрагмент документа'],
  ['DELETE_FRAGMENT', 'удалить фрагмент документа'],
  ['DELETE_FRAGMENTS', 'удалить фрагменты документов'],
  ['CREATE_REQUIREMENT', 'создать требование'],
  ['UPDATE_REQUIREMENT', 'обновить требование'],
  ['DELETE_REQUIREMENT', 'удалить требование'],
  ['DELETE_REQUIREMENTS', 'удалить требования'],
  ['CREATE_COVERAGE', 'создать покрытие требования'],
  ['UPDATE_COVERAGE', 'обновить покрытие требования'],
  ['DELETE_COVERAGE', 'удалить покрытие требования'],
  ['DELETE_COVERAGES', 'удалить покрытия требований'],
  ['CREATE_COMMON_TOPOLOGY', 'создать общую топологию'],
  ['UPDATE_COMMON_TOPOLOGY', 'обновить общую топологию'],
  ['DELETE_COMMON_TOPOLOGY_UNSAFE', 'удалить общую топологию (unsafe)'],
  ['DELETE_COMMON_TOPOLOGY', 'удалить общую топологию'],
  ['DELETE_COMMON_TOPOLOGIES_UNSAFE', 'удалить общие топологии (unsafe)'],
  ['DELETE_COMMON_TOPOLOGIES', 'удалить общие топологии'],
  ['CREATE_TOPOLOGY', 'создать топологию'],
  ['UPDATE_TOPOLOGY', 'обновить топологию'],
  ['DELETE_TOPOLOGY', 'удалить топологию'],
  ['DELETE_TOPOLOGIES', 'удалить топологии'],
  ['CREATE_DSEF', 'создать дополнительный формат'],
  ['UPDATE_DSEF', 'обновить дополнительный формат'],
  ['DELETE_DSEF', 'удалить дополнительный формат'],
  ['DELETE_DSEFS', 'удалить дополнительные форматы'],
  ['CREATE_DBC', 'создать базовую конфигурацию'],
  ['UPDATE_DBC', 'обновить базовую конфигурацию'],
  ['DELETE_DBC', 'удалить базовую конфигурацию'],
  ['DELETE_DBCS', 'удалить базовые конфигурации'],
  ['CREATE_TEST_TEMPLATE', 'создать шаблон теста'],
  ['UPDATE_TEST_TEMPLATE', 'обновить шаблон теста'],
  ['DELETE_TEST_TEMPLATE', 'удалить шаблон теста'],
  ['DELETE_TEST_TEMPLATES', 'удалить шаблоны тестов'],
  ['CREATE_TEST', 'создать тест'],
  ['UPDATE_TEST', 'обновить тест'],
  ['DELETE_TEST', 'удалить тест'],
  ['DELETE_TESTS', 'удалить тесты'],
  ['CREATE_SUBGROUP', 'создать подгруппу'],
  ['UPDATE_SUBGROUP', 'создать подгруппу'],
  ['DELETE_SUBGROUP', 'удалить подгруппу'],
  ['DELETE_SUBGROUPS', 'удалить подгруппы'],
  ['CREATE_GROUP', 'создать группу'],
  ['UPDATE_GROUP', 'обновить группу'],
  ['DELETE_GROUP', 'удалить группу'],
  ['DELETE_GROUPS', 'удалить группы'],
  ['CREATE_DEVICE', 'создать устройство'],
  ['UPDATE_DEVICE', 'обновить устройство'],
  ['DELETE_DEVICE', 'удалить устройство'],
  ['DELETE_DEVICES', 'удалить устройства'],
  ['CREATE_TASK', 'создать задание'],
  ['UPDATE_TASK', 'обновить задание'],
  ['CANCEL_TASK', 'отменить задание'],
  [
    'REACH_TASKS_MIN_LAUNCH_TIME',
    'достигнуть времени минимального запуска задания'
  ],
  ['ABORT_TASK', 'прервать задание'],
  ['PAUSE_TASK', 'поставить задание на паузу'],
  ['UNPAUSE_TASK', 'возобновить задание'],
  ['DELETE_TASK', 'удалить задание'],
  ['DELETE_TASKS', 'удалить задания'],
  ['CREATE_TASK_TEMPLATE', 'создать шаблон задания'],
  ['UPDATE_TASK_TEMPLATE', 'обновить шаблон задания'],
  ['DELETE_TASK_TEMPLATE', 'удалить шаблон задания'],
  ['DELETE_TASK_TEMPLATES', 'удалить шаблоны заданий'],
  ['LAUNCH_TEST', 'запустить тест'],
  ['FINISH_TEST_AS_PASSED', 'завершить тест как пройденный'],
  ['FINISH_TEST_AS_FAILED', 'завершить тест как непройденный'],
  ['FINISH_TEST_AS_ERROR', 'завершить тест как ошибочный'],
  ['CREATE_TEST_REPORT_MESSAGE', 'создать сообщение отчета теста'],
  ['CREATE_TEST_REPORT_MESSAGES', 'создать сообщения отчета теста'],
  ['CREATE_TEST_REPORT_ITEM', 'создать файл отчета теста'],
  ['CREATE_TEST_REPORT_ITEMS', 'создать файлы отчета теста'],
  ['DELETE_TEST_REPORT_ITEM_UNSAFE', 'удалить файл отчета теста'],
  ['DELETE_TEST_REPORT_ITEMS_UNSAFE', 'удалить файлы отчета теста'],
  ['CREATE_SLICE', 'создать срез задания'],
  ['UPDATE_SLICE', 'обновить срез задания'],
  ['DELETE_SLICE', 'удалить срез задания'],
  ['DELETE_SLICES', 'удалить срезы заданий']
])
