// Project
import type { EventType } from '@common/enums'

export const localizationForEventType = new Map<EventType, string>([
  ['CREATE_ROLE', 'создание роли'],
  ['UPDATE_ROLE', 'изменение роли'],
  ['DELETE_ROLE', 'удаление роли'],
  ['DELETE_ROLES', 'удаление ролей'],
  ['CREATE_USER', 'создание пользователя'],
  ['UPDATE_USER', 'изменение пользователя'],
  ['DELETE_USER', 'удаление пользователя'],
  ['DELETE_USERS', 'удаление пользователей'],
  ['CREATE_TAG', 'создание тега'],
  ['UPDATE_TAG', 'изменение тега'],
  ['DELETE_TAG', 'удаление тега'],
  ['DELETE_TAGS', 'удаление тегов'],
  ['CREATE_DOCUMENT', 'создание документа'],
  ['UPDATE_DOCUMENT', 'изменение документа'],
  ['DELETE_DOCUMENT', 'удаление документа'],
  ['DELETE_DOCUMENTS', 'удаление документов'],
  ['CREATE_FRAGMENT', 'создание фрагмента'],
  ['UPDATE_FRAGMENT', 'изменение фрагмента'],
  ['DELETE_FRAGMENT', 'удаление фрагмента'],
  ['DELETE_FRAGMENTS', 'удаление фрагментов'],
  ['CREATE_REQUIREMENT', 'создание требования'],
  ['UPDATE_REQUIREMENT', 'изменение требования'],
  ['DELETE_REQUIREMENT', 'удаление требования'],
  ['DELETE_REQUIREMENTS', 'удаление требований'],
  ['CREATE_COVERAGE', 'создание покрытия'],
  ['UPDATE_COVERAGE', 'изменение покрытия'],
  ['DELETE_COVERAGE', 'удаление покрытия'],
  ['DELETE_COVERAGES', 'удаление покрытий'],
  ['CREATE_COMMON_TOPOLOGY', 'создание общей топологии'],
  ['UPDATE_COMMON_TOPOLOGY', 'изменение общей топологии'],
  ['DELETE_COMMON_TOPOLOGY', 'удаление общей топологии'],
  ['DELETE_COMMON_TOPOLOGIES', 'удаление общих топологий'],
  ['CREATE_TOPOLOGY', 'создание топологии'],
  ['UPDATE_TOPOLOGY', 'изменение топологии'],
  ['DELETE_TOPOLOGY', 'удаление топологии'],
  ['DELETE_TOPOLOGIES', 'удаление топологий'],
  ['CREATE_DSEF', 'создание доп. формата'],
  ['UPDATE_DSEF', 'изменение доп. формата'],
  ['DELETE_DSEF', 'удаление доп. формата'],
  ['DELETE_DSEFS', 'удаление доп. форматов'],
  ['CREATE_DBC', 'создание базовой конфигурации'],
  ['UPDATE_DBC', 'изменение базовой конфигурации'],
  ['DELETE_DBC', 'удаление базовой конфигурации'],
  ['DELETE_DBCS', 'удаление базовых конфигураций'],
  ['CREATE_TEST_TEMPLATE', 'создание шаблона теста'],
  ['UPDATE_TEST_TEMPLATE', 'изменение шаблона теста'],
  ['DELETE_TEST_TEMPLATE', 'удаление шаблона теста'],
  ['DELETE_TEST_TEMPLATES', 'удаление шаблонов тестов'],
  ['CREATE_TEST', 'создание теста'],
  ['UPDATE_TEST', 'изменение теста'],
  ['DELETE_TEST', 'удаление теста'],
  ['DELETE_TESTS', 'удаление тестов'],
  ['CREATE_SUBGROUP', 'создание подгруппы'],
  ['UPDATE_SUBGROUP', 'изменение подгруппы'],
  ['DELETE_SUBGROUP', 'удаление подгруппы'],
  ['DELETE_SUBGROUPS', 'удаление подгрупп'],
  ['CREATE_GROUP', 'создание группы'],
  ['UPDATE_GROUP', 'изменение группы'],
  ['DELETE_GROUP', 'удаление группы'],
  ['DELETE_GROUPS', 'удаление групп'],
  ['CREATE_DEVICE', 'создание устройства'],
  ['UPDATE_DEVICE', 'изменение устройства'],
  ['DELETE_DEVICE', 'удаление устройства'],
  ['DELETE_DEVICES', 'удаление устройств'],
  ['CREATE_TASK', 'создание задания'],
  ['UPDATE_TASK', 'изменение задания'],
  ['CANCEL_TASK', 'отмена задания'],
  ['LAUNCH_TASK', 'запуск задания'],
  ['ABORT_TASK', 'прерывание задания'],
  ['COMPLETE_TASK', 'завершение задания'],
  ['PAUSE_TASK', 'приостановка задания'],
  ['UNPAUSE_TASK', 'возобновление задания'],
  ['DELETE_TASK', 'удаление задания'],
  ['DELETE_TASKS', 'удаление заданий'],
  ['CREATE_TASK_TEMPLATE', 'создание шаблона задания'],
  ['UPDATE_TASK_TEMPLATE', 'изменение шаблона задания'],
  ['DELETE_TASK_TEMPLATE', 'удаление шаблона задания'],
  ['DELETE_TASK_TEMPLATES', 'удаление шаблонов заданий'],
  ['LAUNCH_TEST', 'запуск теста'],
  ['FINISH_TEST_AS_PASSED', 'завершение теста (успех)'],
  ['FINISH_TEST_AS_FAILED', 'завершение теста (неуспех)'],
  ['FINISH_TEST_AS_ERROR', 'завершение теста (ошибка)'],
  ['CREATE_SLICE', 'создание среза'],
  ['UPDATE_SLICE', 'изменение среза'],
  ['DELETE_SLICE', 'удаление среза'],
  ['DELETE_SLICES', 'удаление срезов']
])
