// Project
import type { Right } from '@common/enums'

export const localizationForRight = new Map<Right, string>([
  ['CLEAR_ALL', 'удаление всех данных системы'],
  ['READ_LOGS', 'чтение логов'],
  ['READ_ACTION', 'чтение действий'],
  ['READ_EVENT', 'чтение событий'],
  ['CREATE_ROLE', 'создание ролей'],
  ['READ_ROLE', 'чтение ролей'],
  ['UPDATE_ROLE', 'изменение ролей'],
  ['DELETE_ROLE', 'удаление ролей'],
  ['CREATE_USER', 'создание пользователей'],
  ['READ_USER', 'чтение пользователей'],
  ['READ_SELF', 'чтение себя'],
  ['UPDATE_USER', 'изменение пользователей'],
  ['UPDATE_SELF', 'изменение себя'],
  ['UPDATE_USER_PASS', 'изменение паролей пользователей'],
  ['UPDATE_SELF_PASS', 'изменение собственного пароля'],
  ['DELETE_USER', 'удаление пользователей'],
  ['DELETE_SELF', 'удаление себя'],
  ['CREATE_TAG', 'создание тегов'],
  ['READ_TAG', 'чтение тегов'],
  ['UPDATE_TAG', 'изменение тегов'],
  ['DELETE_TAG', 'удаление тегов'],
  ['CREATE_DOCUMENT', 'создание документов'],
  ['READ_DOCUMENT', 'чтение документов'],
  ['UPDATE_DOCUMENT', 'обновление документов'],
  ['DELETE_DOCUMENT', 'удаление документов'],
  ['CREATE_FRAGMENT', 'создание фрагментов документов'],
  ['READ_FRAGMENT', 'чтение фрагментов документов'],
  ['UPDATE_FRAGMENT', 'изменение фрагментов документов'],
  ['DELETE_FRAGMENT', 'удаление фрагментов документов'],
  ['CREATE_REQUIREMENT', 'создание требований'],
  ['READ_REQUIREMENT', 'чтение требований'],
  ['UPDATE_REQUIREMENT', 'изменение требований'],
  ['DELETE_REQUIREMENT', 'удаление требований'],
  ['CREATE_COVERAGE', 'создание покрытий'],
  ['READ_COVERAGE', 'чтение покрытий'],
  ['UPDATE_COVERAGE', 'изменение покрытий'],
  ['DELETE_COVERAGE', 'удаление покрытий'],
  ['CREATE_COMMON_TOPOLOGY', 'создание общих топологий'],
  ['READ_COMMON_TOPOLOGY', 'чтение общих топологий'],
  ['UPDATE_COMMON_TOPOLOGY', 'изменение общих топологий'],
  ['DELETE_COMMON_TOPOLOGY', 'удаление общих топологий'],
  ['CREATE_TOPOLOGY', 'создание топологий'],
  ['READ_TOPOLOGY', 'чтение топологий'],
  ['UPDATE_TOPOLOGY', 'изменение топологий'],
  ['DELETE_TOPOLOGY', 'удаление топологий'],
  ['CREATE_DSEF', 'создание дополнительных форматов'],
  ['READ_DSEF', 'чтение дополнительных форматов'],
  ['UPDATE_DSEF', 'изменение дополнительных форматов'],
  ['DELETE_DSEF', 'удаление дополнительных форматов'],
  ['CREATE_DBC', 'создание базовых конфигураций'],
  ['READ_DBC', 'чтение базовых конфигураций'],
  ['UPDATE_DBC', 'изменение базовых конфигураций'],
  ['DELETE_DBC', 'удаление базовых конфигураций'],
  ['CREATE_TEST_TEMPLATE', 'создание шаблонов тестов'],
  ['READ_TEST_TEMPLATE', 'чтение шаблонов тестов'],
  ['UPDATE_TEST_TEMPLATE', 'изменение шаблонов тестов'],
  ['DELETE_TEST_TEMPLATE', 'удаление шаблонов тестов'],
  ['CREATE_TEST', 'создание тестов'],
  ['READ_TEST', 'чтение тестов'],
  ['UPDATE_TEST', 'изменение тестов'],
  ['DELETE_TEST', 'удаление тестов'],
  ['CREATE_SUBGROUP', 'создание подгрупп'],
  ['READ_SUBGROUP', 'чтение подгрупп'],
  ['UPDATE_SUBGROUP', 'изменение подгрупп'],
  ['DELETE_SUBGROUP', 'удаление подгрупп'],
  ['CREATE_GROUP', 'создание групп'],
  ['READ_GROUP', 'чтение групп'],
  ['UPDATE_GROUP', 'изменение групп'],
  ['DELETE_GROUP', 'удаление групп'],
  ['CREATE_DEVICE', 'создание устройств'],
  ['READ_DEVICE', 'чтение устройств'],
  ['UPDATE_DEVICE', 'изменение устройств'],
  ['DELETE_DEVICE', 'удаление устройств'],
  ['CREATE_TASK', 'создание заданий'],
  ['READ_TASK', 'чтение заданий'],
  ['READ_TEST_TO_EXECUTE', 'чтение тестов с целью запуска'],
  ['CANCEL_TASK', 'отмена заданий'],
  ['ABORT_TASK', 'прерывание заданий'],
  ['PAUSE_TASK', 'постановка заданий на паузу'],
  ['UNPAUSE_TASK', 'возобновление заданий'],
  ['UPDATE_TASK', 'изменение заданий'],
  ['DELETE_TASK', 'удаление заданий'],
  ['CREATE_TASK_TEMPLATE', 'создание шаблонов заданий'],
  ['READ_TASK_TEMPLATE', 'чтение шаблонов заданий'],
  ['UPDATE_TASK_TEMPLATE', 'изменение шаблонов заданий'],
  ['DELETE_TASK_TEMPLATE', 'удаление шаблонов заданий'],
  ['LAUNCH_TEST', 'запуск заданий'],
  ['FINISH_TEST', 'завершение заданий'],
  [
    'CREATE_TEST_REPORT_MESSAGE',
    'создание сообщений для отчетов о выполнении тестов'
  ],
  [
    'CREATE_TEST_REPORT_ITEM',
    'создание файлов для отчетов о выполнении тестов'
  ],
  ['DELETE_TEST_REPORT_ITEM', 'удаление файлов из отчетов о выполнении тестов'],
  ['READ_TEST_REPORT', 'чтение отчетов о выполнении тестов'],
  ['UPDATE_TEST_REPORT', 'изменение отчетов о выполнении тестов'],
  ['DELETE_TEST_REPORT', 'удаление отчетов о выполнении тестов'],
  ['READ_SUBGROUP_REPORT', 'чтение отчетов о выполнении подгрупп'],
  ['READ_GROUP_REPORT', 'чтение отчетов о выполнении групп'],
  ['READ_TASK_REPORT', 'чтение отчетов о выполнении заданий'],
  ['CREATE_SLICE', 'создание срезов заданий'],
  ['READ_SLICE', 'чтение срезов заданий'],
  ['UPDATE_SLICE', 'изменение срезов заданий'],
  ['DELETE_SLICE', 'удаление срезов заданий']
])
